spring:
  profiles:
    active: local

  application:
    name: kimkeyring-backend

    datasource:
      driver-class-name: org.mariadb.jdbc.Driver
      url: jdbc:mariadb://localhost:3306/kimkeyring
      username: root
      password: password

    mybatis:
      configuration:
        map-underscore-to-camel-case: true
      tyoe-aliases-package: com.kimkeyring.domain
      mapper-locations: classpath:mybatis/mapper/**/*.xml

    server:
      port: 8080